### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by ifrag-ru** [Sples1/ENT_Hosties#15]
Good evening, help solve the problem, floods in the logs
Mod: https://github.com/TiBarification/Jail-Warden-Pro

L 05/20/2020 - 17:37:43: [SM] Blaming: sm_hosties_e.smx
L 05/20/2020 - 17:37:43: [SM] Call stack trace:
L 05/20/2020 - 17:37:43: [SM]   [0] ThrowError
L 05/20/2020 - 17:37:43: [SM]   [1] Line 444, C:\Users\Sples\Desktop\Scripting\XD\include\entity_prop_stocks.inc::SetEntityRenderColor
L 05/20/2020 - 17:37:43: [SM]   [2] Line 1443, hosties/lastrequest.sp::CleanupLastRequest
L 05/20/2020 - 17:37:43: [SM]   [3] Line 1109, hosties/lastrequest.sp::LastRequest_PlayerDeath
L 05/20/2020 - 17:37:43: [SM]   [5] ForcePlayerSuicide
L 05/20/2020 - 17:37:43: [SM]   [6] Line 6488, hosties/lastrequest.sp::Timer_SafeSlay
L 05/20/2020 - 17:38:18: [SM] Exception reported: SetEntityRenderColor not supported by this mod

**Comment by Sples1** [comment]
Greetings!

Please check out the newest version and if your problem still occurs reply to this thread and I will fix them as soon as possible. <3

Thank you

**Comment by Sples1** [comment]
Issue closed due to inactivity.
