### ISSUE TITLE
Myjailbreak compatibility issue

### ISSUE THREAD

**Issue by cleber1337** [Sples1/ENT_Hosties#16]
The plugin is not working fine with myjailbreak, have a way to fix that?

**Comment by rlevet** [comment]
@cleber1337 what's wrong exactly?

**Comment by Sples1** [comment]
Greetings @cleber1337 !

Please check out the newest version and if your problem still occurs reply to this thread and I will fix them as soon as possible. <3
If you find the problem again please describe it as you can. :P

Thank you

**Comment by Sples1** [comment]
Issue closed due to inactivity. You can open a new one if you have any issue.

**Comment by Sples1** [comment]
Issue closed due to inactivity. You can open a new one if you have any issue.
