### ISSUE TITLE
Invalid timer handle

### ISSUE THREAD

**Issue by Septembers** [Sples1/ENT_Hosties#17]
hello entity :)
version 3.1.21b

L 08/26/2020 - 16:44:18: [SM] Exception reported: Invalid timer handle 89550b2a (error 1)
L 08/26/2020 - 16:44:18: [SM] Blaming: jail/sm_hosties_e.smx
L 08/26/2020 - 16:44:18: [SM] Call stack trace:
L 08/26/2020 - 16:44:18: [SM]   [0] KillTimer
L 08/26/2020 - 16:44:18: [SM]   [1] Line 1575, hosties/lastrequest.sp::CleanupLastRequest
L 08/26/2020 - 16:44:18: [SM]   [2] Line 1044, hosties/lastrequest.sp::StopActiveLRs
L 08/26/2020 - 16:44:18: [SM]   [3] Line 1035, hosties/lastrequest.sp::Command_CancelLR

**Comment by Sples1** [comment]
Please check the newest version and reply to this thread if it's still a problem. Also you are a Trusted member in the developer Discord so you can report bugs there to let me see them instantly. <3

Greetings,
Entity

**Comment by Sples1** [comment]
Issue closed due to inactivity. You can open a new one if you have any issue.
