### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by ifrag-ru** [Sples1/ENT_Hosties#20]
L 10/29/2020 - 21:23:24: [SM] Exception reported: SetEntityRenderColor not supported by this mod
L 10/29/2020 - 21:23:24: [SM] Blaming: sm_hosties_e.smx
L 10/29/2020 - 21:23:24: [SM] Call stack trace:
L 10/29/2020 - 21:23:24: [SM]   [0] ThrowError
L 10/29/2020 - 21:23:24: [SM]   [1] Line 444, C:\Users\Sples\Desktop\Scripting\XD\include\entity_prop_stocks.inc::SetEntityRenderColor
L 10/29/2020 - 21:23:24: [SM]   [2] Line 1443, hosties/lastrequest.sp::CleanupLastRequest
L 10/29/2020 - 21:23:24: [SM]   [3] Line 1109, hosties/lastrequest.sp::LastRequest_PlayerDeath
L 10/29/2020 - 21:23:24: [SM]   [5] ForcePlayerSuicide
L 10/29/2020 - 21:23:24: [SM]   [6] Line 6499, hosties/lastrequest.sp::Timer_SafeSlay
L 10/29/2020 - 21:47:23: Error log file session closed.

**Comment by Sples1** [comment]
Could you give me your Hosties version please?

**Comment by Sples1** [comment]
**Ticket closed, because the used version is old and lack of informations.**
