### ISSUE TITLE
error log [New release]

### ISSUE THREAD

**Issue by dimahail** [Sples1/ENT_Hosties#24]
`L 01/07/2021 - 17:31:47: [SM] Exception reported: Array index out-of-bounds (index 19, limit 18)
L 01/07/2021 - 17:31:47: [SM] Blaming: sm_hosties_e.smx
L 01/07/2021 - 17:31:47: [SM] Call stack trace:
L 01/07/2021 - 17:31:47: [SM]   [1] Line 4754, hosties/lastrequest.sp::InitializeGame
L 01/07/2021 - 17:31:47: [SM]   [2] Line 3581, hosties/lastrequest.sp::MainPlayerHandler`

**Comment by Sples1** [comment]
Dear dimahail!

Please check out the next patch. Maybe it's already fixed in it (uploading shortly).
Sorry for late response.
