### ISSUE TITLE
Timer_StripZeus

### ISSUE THREAD

**Issue by ifrag-ru** [Sples1/ENT_Hosties#26]
L 02/02/2021 - 15:31:20: [SM] Exception reported: Invalid index 1 (count: 1)
L 02/02/2021 - 15:31:20: [SM] Blaming: sm_hosties_e.smx
L 02/02/2021 - 15:31:20: [SM] Call stack trace:
L 02/02/2021 - 15:31:20: [SM]   [0] GetArrayCell
L 02/02/2021 - 15:31:20: [SM]   [1] Line 6161, hosties/lastrequest.sp::Timer_StripZeus
L 02/02/2021 - 15:31:51: Error log file session closed.

**Comment by Sples1** [comment]
Dear ifrag-ru!

It's probably patched in next update.
Thanks for you feedback!
