### ISSUE TITLE
[Feature Request] Force LR Rebel if the last TR does not choose any LR option

### ISSUE THREAD

**Issue by crashzk** [Sples1/ENT_Hosties#4]
It would be a good upgrade if you put in the next upgrades the option to force the LR Rebel TR if he does not choose any LR option during X Time.

## How would it work:
It is the last TR alive, there he has 45 seconds to give `!lr` and choose an option, if at this time he does not choose anything, the plugin automatically forces the TR will rebel, and leaves it in the color Red.

Is that possible?

If it is possible, it would be interesting to create a CVAR so that we can set the time the TR has to type `!lr` and if it leaves the LR menu and does not choose an option the time continues from where it stopped, until it chooses one of the LR options or the plugin force it to turn rebel.

@Sples1

**Comment by Sples1** [comment]
### Thank you for your feature request

I will make it in the next update. <3
