### ISSUE TITLE
[BUG] Mute Terrorist in the Beginning of the Round

### ISSUE THREAD

**Issue by crashzk** [Sples1/ENT_Hosties#5]
I have the latest version of the plugin, however I am having several BUGS.

The Prisoner mute at the beginning of the round works, but if the Prisoner changes teams near the end of the round, before starting the new round, it continues to mutate for the time it sets in the plugin's config.

Example, if set to 45 seconds, the prisoners are mutated 45 seconds.

If when the round is over, the Prisoner changes teams, passes to the Guards, he continues mutated at the start of the round for 45 seconds, only after that he can speak into the microphone.
```
L 11/09/2018 - 15:57:07: [SM] Exception reported: Handle e97a15c8 is invalid (error 1)
L 11/09/2018 - 15:57:07: [SM] Blaming: sm_hosties_e.smx
L 11/09/2018 - 15:57:07: [SM] Call stack trace:
L 11/09/2018 - 15:57:07: [SM]   [0] CloseHandle
L 11/09/2018 - 15:57:07: [SM]   [1] Line 271, hosties/muteprisoners.sp::MutePrisoners_RoundEnd
L 11/09/2018 - 15:57:07: [SM]   [3] ChangeClientTeam
L 11/09/2018 - 15:57:07: [SM]   [4] Line 301, teamchange_unlimited.sp::TeamChangeActual
L 11/09/2018 - 15:57:07: [SM]   [5] Line 204, teamchange_unlimited.sp::JoinTeamCmd
```
@Sples1

**Comment by Sples1** [comment]
### Thank you for your report

I'm going to check it out and try to fix it as soon as possible!

**Comment by Sples1** [comment]
Could you please check if it's fixed in the update?

**Comment by Sples1** [comment]
Fixed in the latest build probably.
