### ISSUE TITLE
Bring back guntoss

### ISSUE THREAD

**Issue by Prefix** [Sples1/ENT_Hosties#8]
I don't know why it was removed. But it was good LR and people even making hastags to nicknames to bring it back. Maybe make it optional with convar or as seperate plugin?

**Comment by Sples1** [comment]
I'll add it back. 
Too much request for that.

**Comment by Sples1** [comment]
Please add me On Steam or Discord to talk about it.

**Comment by Sples1** [comment]
GunToss back
